# Generated by Django 4.0.6 on 2022-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='race',
            field=models.CharField(blank=True, choices=[('w', 'White'), ('b', 'Black/African American'), ('a', 'Asian'), ('h', 'Hispanic/Latino'), ('o', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_name',
            field=models.CharField(choices=[('1', '1st District'), ('2', '2nd District'), ('3', '3rd District'), ('4', '4th District'), ('5', '5th District'), ('6', '6th District'), ('7', '7th District'), ('8', '8th District'), ('9', '9th District'), ('10', '10th District'), ('AL', 'At Large')], max_length=2, unique=True),
        ),
    ]
