# Generated by Django 4.0.6 on 2022-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0004_alter_person_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
