# Generated by Django 4.0.6 on 2022-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0005_alter_person_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('o', 'Non-binary/other')], max_length=1, null=True),
        ),
    ]
