# Generated by Django 4.0.6 on 2022-10-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0006_person_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='election',
            unique_together={('election_date', 'election_type', 'election_seat')},
        ),
    ]
