# Generated by Django 4.0.6 on 2022-10-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0014_term_correct_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='term',
            name='correct_datetime',
        ),
    ]
