# Generated by Django 4.0.6 on 2022-10-03 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0016_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['election_date', 'election_type', 'election_seat']},
        ),
    ]
