# Generated by Django 4.0.6 on 2022-10-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0017_alter_election_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['candidate_election__election_seat']},
        ),
    ]
