# Generated by Django 4.0.6 on 2022-10-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0018_alter_candidate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['candidate_election__election_seat__seat_name']},
        ),
    ]
