# Generated by Django 4.0.6 on 2022-10-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0019_alter_candidate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_name']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['term_start_date', 'term_end_date', 'councilmember__candidate_person__last_name']},
        ),
    ]
