# Generated by Django 4.0.6 on 2022-10-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0021_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_votes_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
