# Generated by Django 4.0.6 on 2022-10-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0022_candidate_candidate_votes_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='left_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='left_early',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
