# Generated by Django 4.0.6 on 2022-11-05 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0025_alter_candidate_candidate_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phlcitycouncil.election'),
        ),
    ]
