# Generated by Django 4.0.6 on 2022-11-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0027_alter_candidate_candidate_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican'), ('i', 'Independent'), ('l', 'Libertarian'), ('wf', 'Working Families Party'), ('p', 'Progressive')], default='', max_length=3, null=True),
        ),
    ]
