# Generated by Django 4.0.6 on 2022-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0030_alter_election_election_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_party',
            field=models.CharField(choices=[('na', ''), ('d', 'Democrat'), ('r', 'Republican'), ('i', 'Independent'), ('l', 'Libertarian'), ('wf', 'Working Families Party'), ('p', 'Progressive')], default='na', max_length=3),
        ),
    ]
