# Generated by Django 4.0.6 on 2022-11-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0031_alter_election_election_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phlcitycouncil.person'),
        ),
    ]
