# Generated by Django 4.0.6 on 2023-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlcitycouncil', '0032_alter_candidate_candidate_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_party',
            field=models.CharField(choices=[('na', ''), ('d', 'Democrat'), ('r', 'Republican'), ('i', 'Independent'), ('l', 'Libertarian'), ('wf', 'Working Families Party'), ('p', 'Progressive'), ('tlp', 'Term Limits Philadelphia Party')], default='na', max_length=3),
        ),
    ]
